server:
    port: 9000
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.2.3:3306/
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    root: info
    org:
      springframework:
        web: info
#  file: logs
#  config: logback.xml
  pattern:
    file: 1%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %n
    console: 2%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %n
    level: 3%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg %n
#  typeAliasesPackage:
